=== Simon-Initiative/oli-torus/priv/schemas/v0-1-0/activity.schema.json
{
  "$id": "http://torus.oli.cmu.edu/schemas/v0-1-0/activity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Activity",
  "description": "An activity",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "const": "Activity"
    },
    "subType": {
      "type": "string"
    },
    "content": {
      "$ref": "http://torus.oli.cmu.edu/schemas/v0-1-0/activity-content.schema.json"
    },
    "objectives": {},
    "originalFile": {
      "type": "string"
    },
    "tags": {
      "type": "array"
    },
    "title": {
      "type": "string"
    },
    "unresolvedReferences": {
      "type": "array"
    }
  },
  "required": [
    "id",
    "type",
    "subType",
    "content",
    "title"
  ]
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/42.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "3566865719",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "217373385"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "117464798",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "869553798"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "4068053049",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "3850651137"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Yes"
                        }
                      ],
                      "id": "35502516",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 3,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 3,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "2230602088"
              },
              "id": "3872260861",
              "rule": "input like {1140798647}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Beyos is an Asturian cheese, but Cabrales is the cheese that Asturias is most well known for"
                        }
                      ],
                      "id": "2887735398",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 92,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 92,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "3533203050"
              },
              "id": "1692219054",
              "rule": "input like {2264915565}",
              "score": 0
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No, that is an English cheese"
                        }
                      ],
                      "id": "1789533583",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 29,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 29,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "855053315"
              },
              "id": "584678291",
              "rule": "input like {4238456170}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Which cheese is Asturias most famous for?",
      "transformations": [
        {
          "id": "2999345774",
          "operation": "shuffle",
          "path": "choices"
        }
      ]
    },
    "choices": [
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Cabrales"
                }
              ],
              "id": "2615119788",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 8,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 8,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "1140798647"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Beyos"
                }
              ],
              "id": "3699718668",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 5,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 5,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "2264915565"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Stilton"
                }
              ],
              "id": "3338613821",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 7,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 7,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "4238456170"
      }
    ],
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "Which cheese is Asturias most famous for?"
              }
            ],
            "id": "3461753632",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 41,
            "path": [
              0,
              0
            ]
          },
          "focus": {
            "offset": 41,
            "path": [
              0,
              0
            ]
          }
        }
      },
      "id": "1120144535"
    }
  },
  "id": "42",
  "objectives": {
    "1": [
      "23"
    ]
  },
  "originalFile": "",
  "subType": "oli_multiple_choice",
  "tags": [],
  "title": "MCQ Asturian Dish",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/2689.json
{
  "content": {
    "authoring": {
      "correct": [
        [
          "197359854",
          "2262107079"
        ],
        "4075191741"
      ],
      "incorrect": [
        [
          "2891433049"
        ],
        "356707875"
      ],
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "2427668079",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2311357842"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "2106922201",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "1251387669"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "1760727316",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "1200885668"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Yes"
                        }
                      ],
                      "id": "1653132021",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 3,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 3,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "573816189"
              },
              "id": "4075191741",
              "rule": "(!(input like {2891433049})) && (input like {2262107079} && (input like {197359854}))",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No"
                        }
                      ],
                      "id": "3606749900",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 2,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 2,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "191277972"
              },
              "id": "356707875",
              "rule": "(!((!(input like {2891433049})) && (input like {2262107079} && (input like {197359854}))))",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Check all that apply: 1 and 2 are correct",
      "transformations": [
        {
          "id": "1585711933",
          "operation": "shuffle",
          "path": "choices"
        }
      ]
    },
    "choices": [
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Choice 1"
                }
              ],
              "id": "826091067",
              "type": "p"
            }
          ],
          "selection": null
        },
        "id": "197359854"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Choice 2"
                }
              ],
              "id": "493978474",
              "type": "p"
            }
          ],
          "selection": null
        },
        "id": "2262107079"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Three"
                }
              ],
              "id": "2963847984",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 5,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 5,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "2891433049"
      }
    ],
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "Check all that apply: 1 and 2 are correct"
              }
            ],
            "id": "3697009323",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 41,
            "path": [
              0,
              0
            ]
          },
          "focus": {
            "offset": 41,
            "path": [
              0,
              0
            ]
          }
        }
      },
      "id": "3445719549"
    },
    "type": "SimpleCATA"
  },
  "id": "2689",
  "objectives": {
    "1": []
  },
  "originalFile": "",
  "subType": "oli_check_all_that_apply",
  "tags": [],
  "title": "Check All That Apply",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/1075.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "1290850083",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2547880742"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "1009820392",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "1358400294"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "1996882609",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2060948831"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": ""
                        }
                      ],
                      "id": "996045821",
                      "type": "p"
                    }
                  ],
                  "selection": null
                },
                "id": "740082385"
              },
              "id": "3403914227",
              "rule": "input like {answerj}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": ""
                        }
                      ],
                      "id": "278096631",
                      "type": "p"
                    }
                  ],
                  "selection": null
                },
                "id": "1248615824"
              },
              "id": "2996671916",
              "rule": "input like {.*}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "",
      "transformations": []
    },
    "inputType": "text",
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": ""
              }
            ],
            "id": "2042882888",
            "type": "p"
          }
        ],
        "selection": null
      },
      "id": "2682336924"
    }
  },
  "id": "1075",
  "objectives": {
    "1": []
  },
  "originalFile": "",
  "subType": "oli_short_answer",
  "tags": [],
  "title": "Single Response",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/8545.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": [
                {
                  "children": [
                    {
                      "text": ""
                    }
                  ],
                  "id": "1583563843",
                  "type": "p"
                }
              ],
              "id": "2194690253"
            },
            {
              "content": [
                {
                  "children": [
                    {
                      "text": ""
                    }
                  ],
                  "id": "2372226075",
                  "type": "p"
                }
              ],
              "id": "2164090013"
            },
            {
              "content": [
                {
                  "children": [
                    {
                      "text": ""
                    }
                  ],
                  "id": "3673201587",
                  "type": "p"
                }
              ],
              "id": "2195675847"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": [
                  {
                    "children": [
                      {
                        "text": "Correct"
                      }
                    ],
                    "id": "2359639415",
                    "type": "p"
                  }
                ],
                "id": "2550509729"
              },
              "id": "3244383511",
              "rule": "input like {656240064}",
              "score": 1
            },
            {
              "feedback": {
                "content": [
                  {
                    "children": [
                      {
                        "text": "Incorrect"
                      }
                    ],
                    "id": "3368139561",
                    "type": "p"
                  }
                ],
                "id": "2584744407"
              },
              "id": "3230397878",
              "rule": "input like {.*}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Let's try \" a < > test",
      "targeted": [],
      "transformations": [
        {
          "id": "1291733059",
          "operation": "shuffle",
          "path": "choices"
        }
      ],
      "version": 2
    },
    "choices": [
      {
        "content": [
          {
            "children": [
              {
                "text": "Choice A"
              }
            ],
            "id": "3791029652",
            "type": "p"
          }
        ],
        "id": "656240064"
      },
      {
        "content": [
          {
            "children": [
              {
                "text": "Choice B"
              }
            ],
            "id": "3330267716",
            "type": "p"
          }
        ],
        "id": "1201447932"
      }
    ],
    "stem": {
      "content": [
        {
          "children": [
            {
              "text": "Let's try \" a < > test"
            }
          ],
          "id": "4152282852",
          "type": "p"
        }
      ],
      "id": "794192279"
    }
  },
  "id": "8545",
  "objectives": {
    "1": []
  },
  "originalFile": "",
  "subType": "oli_multiple_choice",
  "tags": [],
  "title": "Multiple Choice",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/6534.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "808241945",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "3132831464"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "3536072053",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2570023658"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "1325038514",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "656340057"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": ""
                        }
                      ],
                      "id": "352433106",
                      "type": "p"
                    }
                  ],
                  "selection": null
                },
                "id": "3885040791"
              },
              "id": "1812450947",
              "rule": "input like {2283591575}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": ""
                        }
                      ],
                      "id": "303808502",
                      "type": "p"
                    }
                  ],
                  "selection": null
                },
                "id": "3511779953"
              },
              "id": "4024272330",
              "rule": "input like {.*}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "This is a test question two.",
      "targeted": [],
      "transformations": [
        {
          "id": "3848365531",
          "operation": "shuffle",
          "path": "choices"
        }
      ],
      "version": 2
    },
    "choices": [
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Choice A"
                }
              ],
              "id": "2000890955",
              "type": "p"
            }
          ],
          "selection": null
        },
        "id": "2283591575"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Choice B"
                }
              ],
              "id": "3211484742",
              "type": "p"
            }
          ],
          "selection": null
        },
        "id": "2246257437"
      }
    ],
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "This is a test question two."
              }
            ],
            "id": "32040149",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 28,
            "path": [
              0,
              0
            ]
          },
          "focus": {
            "offset": 28,
            "path": [
              0,
              0
            ]
          }
        }
      },
      "id": "38780621"
    }
  },
  "id": "6534",
  "objectives": {
    "1": [
      "25"
    ]
  },
  "originalFile": "",
  "subType": "oli_multiple_choice",
  "tags": [],
  "title": "Multiple Choice",
  "type": "Activity",
  "unresolvedReferences": []
}
