=== Simon-Initiative/oli-torus/priv/schemas/v0-1-0/activity.schema.json
{
  "$id": "http://torus.oli.cmu.edu/schemas/v0-1-0/activity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Activity",
  "description": "An activity",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "type": {
      "const": "Activity"
    },
    "subType": {
      "type": "string"
    },
    "content": {
      "$ref": "http://torus.oli.cmu.edu/schemas/v0-1-0/activity-content.schema.json"
    },
    "objectives": {},
    "originalFile": {
      "type": "string"
    },
    "tags": {
      "type": "array"
    },
    "title": {
      "type": "string"
    },
    "unresolvedReferences": {
      "type": "array"
    }
  },
  "required": [
    "id",
    "type",
    "subType",
    "content",
    "title"
  ]
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/37.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": "Reread the section on Fabada"
                      }
                    ],
                    "id": "554200302",
                    "type": "p"
                  }
                ],
                "selection": {
                  "anchor": {
                    "offset": 28,
                    "path": [
                      0,
                      0
                    ]
                  },
                  "focus": {
                    "offset": 28,
                    "path": [
                      0,
                      0
                    ]
                  }
                }
              },
              "id": "4211592617"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "3722660994",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2978023576"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "2863130404",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "603822508"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Correct"
                        }
                      ],
                      "id": "1153519480",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 7,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 7,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "1048586312"
              },
              "id": "3737290472",
              "rule": "input like {404488393}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No, fabada is a bean stew"
                        }
                      ],
                      "id": "914670944",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 25,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 25,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "167425920"
              },
              "id": "2444037469",
              "rule": "input like {1848271280}",
              "score": 0
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No, goat meat is not included in a traditional fabada"
                        }
                      ],
                      "id": "3727940334",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 53,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 53,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "1141310182"
              },
              "id": "3124911495",
              "rule": "input like {3962178651}",
              "score": 0
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No, eggs are not part of this dish"
                        }
                      ],
                      "id": "4031710834",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 34,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 34,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "2656891518"
              },
              "id": "1946464972",
              "rule": "input like {4145534410}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Fabada is a stew made of:",
      "transformations": [
        {
          "id": "1847161949",
          "operation": "shuffle",
          "path": "choices"
        }
      ]
    },
    "choices": [
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Beans and pork"
                }
              ],
              "id": "297963205",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 14,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 14,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "404488393"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Shellfish"
                }
              ],
              "id": "4185483583",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 9,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 9,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "1848271280"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Mountain goat"
                }
              ],
              "id": "707392175",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 13,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 13,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "3962178651"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Eggs"
                }
              ],
              "id": "1308637018",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 4,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 4,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "4145534410"
      }
    ],
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "Fabada is a stew made of:"
              }
            ],
            "id": "3557333685",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 25,
            "path": [
              0,
              0
            ]
          },
          "focus": {
            "offset": 25,
            "path": [
              0,
              0
            ]
          }
        }
      },
      "id": "623463683"
    }
  },
  "id": "37",
  "objectives": {
    "1": [
      "27",
      "26",
      "23"
    ]
  },
  "originalFile": "",
  "subType": "oli_multiple_choice",
  "tags": [
    "id2"
  ],
  "title": "MCQ Fabada Ingredients",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/44.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "373612778",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "2028991487"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "4153232947",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "3158490711"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "34826459",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "379751068"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Thanks"
                        }
                      ],
                      "id": "3999202723",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 6,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 6,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "1047164986"
              },
              "id": "3374546649",
              "rule": "input like {*}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Thanks"
                        }
                      ],
                      "id": "3012661872",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 6,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 6,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "2181959411"
              },
              "id": "3632849809",
              "rule": "input like {.*}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Please comment on your experience with this course.  This has no bearing on your grade. ",
      "transformations": []
    },
    "inputType": "text",
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "Please "
              },
              {
                "strong": true,
                "text": "comment"
              },
              {
                "text": " on your experience with this course.  This has no bearing on your grade. "
              }
            ],
            "id": "588476085",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 0,
            "path": [
              0,
              1
            ]
          },
          "focus": {
            "offset": 7,
            "path": [
              0,
              1
            ]
          }
        }
      },
      "id": "916234183"
    }
  },
  "id": "44",
  "objectives": {
    "1": []
  },
  "originalFile": "",
  "subType": "oli_short_answer",
  "tags": [],
  "title": "Single Response",
  "type": "Activity",
  "unresolvedReferences": []
}

=== Simon-Initiative/oli-torus/test/oli/interop/digest/36.json
{
  "content": {
    "authoring": {
      "parts": [
        {
          "hints": [
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": "Reread the Cider section"
                      }
                    ],
                    "id": "1045392128",
                    "type": "p"
                  }
                ],
                "selection": {
                  "anchor": {
                    "offset": 24,
                    "path": [
                      0,
                      0
                    ]
                  },
                  "focus": {
                    "offset": 24,
                    "path": [
                      0,
                      0
                    ]
                  }
                }
              },
              "id": "1235839873"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "4164872574",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "3976065050"
            },
            {
              "content": {
                "model": [
                  {
                    "children": [
                      {
                        "text": ""
                      }
                    ],
                    "id": "3918483939",
                    "type": "p"
                  }
                ],
                "selection": null
              },
              "id": "3176785033"
            }
          ],
          "id": "1",
          "responses": [
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "Correct"
                        }
                      ],
                      "id": "3582318604",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 7,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 7,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "2387390274"
              },
              "id": "3651814675",
              "rule": "input like {3889942927}",
              "score": 1
            },
            {
              "feedback": {
                "content": {
                  "model": [
                    {
                      "children": [
                        {
                          "text": "No, Asturian cider is actually dry"
                        }
                      ],
                      "id": "2671149804",
                      "type": "p"
                    }
                  ],
                  "selection": {
                    "anchor": {
                      "offset": 34,
                      "path": [
                        0,
                        0
                      ]
                    },
                    "focus": {
                      "offset": 34,
                      "path": [
                        0,
                        0
                      ]
                    }
                  }
                },
                "id": "760048381"
              },
              "id": "3541772352",
              "rule": "input like {584457882}",
              "score": 0
            }
          ],
          "scoringStrategy": "average"
        }
      ],
      "previewText": "Why is Asturian Cider typically poured from a height above one's head?",
      "transformations": [
        {
          "id": "2770901034",
          "operation": "shuffle",
          "path": "choices"
        }
      ]
    },
    "choices": [
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "The oxygenation adds carbonation and a bit of flavor to the cider"
                }
              ],
              "id": "402867328",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 38,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 38,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "3889942927"
      },
      {
        "content": {
          "model": [
            {
              "children": [
                {
                  "text": "Cider is naturally sweet and this pouring style enhances that sweetness"
                }
              ],
              "id": "1154344617",
              "type": "p"
            }
          ],
          "selection": {
            "anchor": {
              "offset": 71,
              "path": [
                0,
                0
              ]
            },
            "focus": {
              "offset": 71,
              "path": [
                0,
                0
              ]
            }
          }
        },
        "id": "584457882"
      }
    ],
    "stem": {
      "content": {
        "model": [
          {
            "children": [
              {
                "text": "Why is Asturian Cider typically poured from a height above one's head?"
              }
            ],
            "id": "105251297",
            "type": "p"
          }
        ],
        "selection": {
          "anchor": {
            "offset": 70,
            "path": [
              0,
              0
            ]
          },
          "focus": {
            "offset": 70,
            "path": [
              0,
              0
            ]
          }
        }
      },
      "id": "2514266211"
    }
  },
  "id": "36",
  "objectives": {
    "1": [
      "28"
    ]
  },
  "originalFile": "",
  "subType": "oli_multiple_choice",
  "tags": [
    "id1"
  ],
  "title": "MCQ Sidre Pour Height",
  "type": "Activity",
  "unresolvedReferences": []
}
